# Generated by Django 4.0.4 on 2022-05-29 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_liked',
            field=models.ManyToManyField(null=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
